### ISSUE TITLE
Configuration support

### ISSUE THREAD

**Issue by TenshiLyle** [CodingAvenue/ca-school-proof-library#17]
Allow user of this library to create a configuration file which will set default location of the code file.

**Comment by TenshiLyle** [comment]
@sandaemc any recommendation for an existing library that I could use for the config finder?

**Comment by TenshiLyle** [comment]
@sandaemc my implementation for this is to use composer post install/update events to create a config file that the Code class will use.

I do have a question about this ticket, if the authors have a proof.json file and we use the value of it. That would mean when the sandbox run the proof file, it will look at the authors define path.

**Comment by sandaemc** [comment]
> I do have a question about this ticket, if the authors have a proof.json file and we use the value of it. That would mean when the sandbox run the proof file, it will look at the authors define path.

Oh yeah, this is a double-edge use case and will only confuse the user. Our purpose for the config is to make testing work locally without sandbox... In sandbox, it must look for `/code` but when we are testing locally, we like to have it somewhere near.

Having config has its advantage though. What if the proof writer like Windows? `/code` is not a valid Windows path so it will be a problem. Our library is limited to Nix based system only.

We need to make it explicit that proof.json's purpose is so that we can override the default sandbox's operation so we can test locally.

**Comment by sandaemc** [comment]
We don't need this. I realized, `code` file can be part of php-proof - relative to the path.

Let's rename it to `.code`  so it can be hidden to writers though. So the proof-lib will always look to `./.code`

**Comment by sandaemc** [comment]
The problem for **where to look for code** is fixed by making it relative to the codebase or php-proof

https://github.com/CodingAvenue/ca-school-sandbox/commit/97fe21c3d6894fff6e3df79bb83f47e4163721a2

**Comment by sandaemc** [comment]
Actually, we're going to have a problem with this approach once when multiple students are submitting code :-(. So ignore this idea. lol

**Comment by sandaemc** [comment]
Let's continue with supporting by config.

**Comment by TenshiLyle** [comment]
This will be implemented on #12.
